### ISSUE TITLE
Update external projects to latest commits

### ISSUE THREAD

**Issue by phcerdan** [Kitware/SlicerSALT#43]
- [x] ShapePopulationViewer: Update when this PR is merged: https://github.com/NIRALUser/ShapePopulationViewer/pull/30. Done in #40 
- [x] Update Sequences. Done in #40 
- [x] Update Slicer. Done in #40, after Slicer updated CTK and backported VTKv9 patch in [04917a6ce74](https://github.com/Slicer/Slicer/commit/04917a6ce74d361c2abc7bdcb06340201953a8c3)
